### ISSUE TITLE
Build phase on Schelling example throws error

### ISSUE THREAD

**Issue by mkostmann** [OpenSourceEconomics/econ-project-templates#85] opened 2020-06-29 14:08 UTC
I am getting this error when running `python waf.py build -j1`

> [5/8] Running  [Python] src/analysis/schelling.py baseline
> [6/8] Running  [Python] src/analysis/schelling.py max_moves_2
> Traceback (most recent call last):
>   File "/Users/XXX/projects/map/src/analysis/schelling.py", line 117, in <module>
>     agents = setup_agents(model)
>   File "/Users/XXX/projects/map/src/analysis/schelling.py", line 28, in setup_agents
>     initial_locations = initial_locations.reshape(2, model["n_types"], 30000)
> **ValueError: cannot reshape array of size 60000 into shape (2,2,30000)**
> 
> Waf: Leaving directory `/Users/XXX/projects/map/bld'
> Build failed
>  -> task in 'schelling_max_moves_2' failed with exit status 1 (run with -v to display more information)

**Comment by hmgaudecker** [comment] 2021-03-23 09:48
I am sorry this slipped through! Last summer was a bit crazy.

Closing this as I cannot reproduce. If it is still relevant, please re-open.

**Closed by hmgaudecker** 2021-03-23 09:48 UTC
